// Banco de preguntas del trivial. Formato: [pregunta, respuesta correcta, otra, otra, otra]
export const BANCO = {
  "Dardos": [
    ["¿Qué número está en la parte superior de un tablero de dardos?", "20", "1", "18", "5"],
    ["¿Cuánto vale el centro del tablero (la diana)?", "50", "25", "100", "75"],
    ["¿Cuál es la puntuación máxima con tres dardos?", "180", "150", "120", "201"],
    ["¿Cuál es el remate más alto posible en un 501?", "170", "160", "180", "150"],
    ["¿Qué número está justo enfrente del 20?", "3", "1", "5", "11"],
    ["¿Cuál es la modalidad de dardos más habitual en competición?", "501", "301", "401", "701"],
    ["¿A qué distancia del tablero se tira en un tablero oficial?", "2,37 m", "1,80 m", "3,00 m", "2,00 m"],
    ["¿A qué altura está el centro del tablero respecto al suelo?", "1,73 m", "1,50 m", "1,90 m", "1,60 m"],
    ["¿Cuál es el mínimo de dardos para completar un 501?", "9", "7", "10", "12"],
    ["En el Cricket, ¿qué números se juegan?", "Del 15 al 20 y la diana", "Del 1 al 10", "Del 10 al 20", "Solo los dobles"],
    ["¿Qué anillo del tablero multiplica la puntuación por tres?", "El anillo interior estrecho", "El anillo exterior estrecho", "La diana central", "El fondo ancho"],
    ["¿Qué se grita cuando alguien consigue la puntuación máxima en una ronda?", "¡Ciento ochenta!", "¡Bingo!", "¡Checkout!", "¡Bullseye!"],
    ["¿Cuánto vale el anillo verde exterior del centro de la diana?", "25", "50", "10", "15"],
    ["¿Cómo se llama en inglés la diana central roja de 50 puntos?", "Bullseye", "Triple crown", "Outer ring", "Double top"],
    ["¿Qué ocurre si sumas más puntos de los que te faltan para llegar a cero?", "Bust (Te pasas)", "Ganas la partida", "Resta el doble", "Pierdes el turno y la partida"],
    ["¿Cómo se le conoce al Doble 20 en el argot de los dardos?", "Tops", "Big Red", "Double Crown", "Bull"],
    ["¿Qué número está a la derecha del 20 en un tablero estándar?", "1", "5", "18", "12"],
    ["¿Qué número está a la izquierda del 20 en un tablero estándar?", "5", "1", "12", "18"],
    ["Para cerrar una partida de 501 tradicional, ¿con qué tipo de casillero se debe terminar?", "Doble o Bullseye", "Triple", "Cualquier impar", "Solo con Bullseye"],
    ["¿Qué dardo es el último en lanzarse en un remate de 170?", "Bullseye", "Doble 20", "Doble 18", "Triple 20"],
    ["¿Cómo se llama la línea en el suelo tras la que se sitúa el jugador?", "Oche", "Toe line", "Foul line", "Darts line"],
    ["¿Cuál es el peso máximo permitido para un dardo de acero en la PDC?", "50 gramos", "30 gramos", "40 gramos", "25 gramos"],
    ["¿De qué material se fabrican las dianas tradicionales de mayor calidad?", "Fibras de sisal", "Corcho", "Plástico", "Madera de balsa"],
    ["¿Qué organismo organiza el World Darts Championship profesional más famoso?", "PDC", "BDO", "WDF", "EDU"],
    ["¿Qué famoso jugador inglés es apodado «The Power»?", "Phil Taylor", "Michael van Gerwen", "Peter Wright", "Gary Anderson"],
    ["¿Qué jugador neerlandés viste de verde y ostenta múltiples títulos mundiales?", "Michael van Gerwen", "Raymond van Barneveld", "Dirk van Duijvenbode", "Danny Noppert"],
    ["¿Qué apodo tiene el carismático jugador escocés Peter Wright?", "Snakebite", "The Power", "The Flying Scotsman", "Mighty Mike"],
    ["En la modalidad de dardos electrónicos, ¿cuál es el peso máximo habitual por dardo?", "20 gramos", "30 gramos", "35 gramos", "12 gramos"],
    ["¿Cómo se le llama al dardo que rebota en el tablero y cae al suelo?", "Bounce out", "Robin Hood", "Bust", "Skimmer"],
    ["¿Qué ocurre cuando un dardo se clava directamente en la caña de otro ya clavado?", "Robin Hood", "Double Hit", "Bust", "Bullseye"],
    ["¿Cuál es el valor de un Triple 19?", "57", "38", "51", "60"],
    ["¿Cuál es el valor de un Triple 17?", "51", "48", "54", "34"],
    ["¿Cuál es la puntuación de un Triple 20?", "60", "40", "50", "30"],
    ["¿Qué combinación suma 40 puntos para cerrar de un solo tiro?", "Doble 20", "Doble 10", "Doble 15", "Doble 18"],
    ["Si te quedan 32 puntos, ¿a qué doble debes apuntar para cerrar?", "Doble 16", "Doble 8", "Doble 12", "Doble 18"],
    ["Si te quedan 16 puntos, ¿a qué doble debes tirar?", "Doble 8", "Doble 4", "Doble 10", "Doble 16"],
    ["¿Cuál es el apodo profesional del jugador galés Gerwyn Price?", "The Iceman", "The Ferret", "The Rockstar", "Bully Boy"],
    ["¿Qué jugador inglés ganó el Mundial PDC 2023 tras realizar un 9-darter en la final?", "Michael Smith", "Luke Humphries", "Rob Cross", "Nathan Aspinall"],
    ["¿Qué joven prodigio británico llegó a la final del Mundial PDC 2024 con 16 años?", "Luke Littler", "Luke Humphries", "Josh Rock", "Beau Greaves"],
    ["En el juego del Cricket, ¿cuántas marcas se necesitan para cerrar un número?", "3", "2", "4", "5"],
    ["En Cricket, ¿cuántas marcas otorga impactar en un sector Triple?", "3 marcas", "1 marca", "2 marcas", "4 marcas"],
    ["En Cricket, ¿cuántas marcas otorga el centro rojo del Bullseye?", "2 marcas", "1 marca", "3 marcas", "4 marcas"],
    ["En el juego «Count Up», ¿cuál es el objetivo principal?", "Sumar el máximo de puntos posible", "Llegar exactamente a cero", "Cerrar los sectores del 15 al 20", "Hacer únicamente dobles"],
    ["En el juego «Around the Clock» (Al Reloj), ¿cuál es el objetivo?", "Acertar en orden los números del 1 al 20", "Sumar 501 puntos rápidamente", "Dar tres veces al Bullseye", "Lograr 100 puntos en un minuto"],
    ["En una diana electrónica, ¿de qué material son las puntas de los dardos?", "Plástico", "Acero", "Aluminio", "Tungsteno"],
    ["¿Qué porcentaje de tungsteno suelen tener los dardos profesionales de acero?", "Entre 80% y 90%", "10%", "30%", "100%"],
    ["¿Cómo se llama la pieza del dardo donde se sujetan las plumas?", "Caña (shaft)", "Punta", "Cuerpo (barrel)", "Rosca"],
    ["¿Cómo se llama el cuerpo principal de metal del dardo que se agarra al tirar?", "Barril (barrel)", "Pluma", "Caña", "Punta"],
    ["¿Qué pieza del dardo ayuda a estabilizar su trayectoria en el aire?", "Pluma (flight)", "Caña", "Punta", "Contrapeso"],
    ["En un 501, si te quedan 40 puntos y aciertas en el 20 simple, ¿cuántos te quedan?", "20", "10", "0", "30"]
  ],
  "Cultura general": [
    ["¿Cuál es la capital de Australia?", "Canberra", "Sídney", "Melbourne", "Perth"],
    ["¿Cuál es el planeta más grande del sistema solar?", "Júpiter", "Saturno", "Neptuno", "La Tierra"],
    ["¿Cuál es el símbolo químico del oro?", "Au", "Ag", "Or", "Go"],
    ["¿Cuántos huesos tiene el cuerpo de un adulto?", "206", "150", "300", "180"],
    ["¿En qué año llegó el ser humano a la Luna?", "1969", "1959", "1975", "1981"],
    ["¿Cuál es el océano más grande del mundo?", "Pacífico", "Atlántico", "Índico", "Ártico"],
    ["¿Quién pintó La Gioconda?", "Leonardo da Vinci", "Miguel Ángel", "Rafael", "Velázquez"],
    ["¿Cuál es el río más largo de la Península Ibérica?", "El Tajo", "El Ebro", "El Duero", "El Guadalquivir"],
    ["¿Cuál es el país más grande del mundo por superficie?", "Rusia", "Canadá", "China", "Estados Unidos"],
    ["¿Qué gas necesitamos respirar para vivir?", "Oxígeno", "Helio", "Hidrógeno", "Metano"],
    ["¿Cuál es el país más poblado del mundo?", "India", "China", "Estados Unidos", "Indonesia"],
    ["¿En qué año cayó el Muro de Berlín?", "1989", "1991", "1975", "1985"],
    ["¿Cuál es el elemento químico más abundante en el universo?", "Hidrógeno", "Helio", "Oxígeno", "Carbono"],
    ["¿Quién escribió «Cien años de soledad»?", "Gabriel García Márquez", "Mario Vargas Llosa", "Julio Cortázar", "Pablo Neruda"],
    ["¿En qué continente se encuentra el desierto del Sahara?", "África", "Asia", "América", "Oceanía"],
    ["¿Cuál es el metal más brillante y reflectante?", "Plata", "Oro", "Platino", "Cobre"],
    ["¿Cuál es el animal terrestre más rápido del mundo?", "Guepardo", "León", "Gacela", "Galgo"],
    ["¿Qué país europeo tiene forma de bota?", "Italia", "Grecia", "Portugal", "España"],
    ["¿Cuál es la capital de Canadá?", "Ottawa", "Toronto", "Montreal", "Vancouver"],
    ["¿Quién descubrió la penicilina?", "Alexander Fleming", "Louis Pasteur", "Marie Curie", "Robert Koch"],
    ["¿Qué científico formuló la Teoría de la Relatividad?", "Albert Einstein", "Isaac Newton", "Niels Bohr", "Galileo Galilei"],
    ["¿Cuál es la isla más grande del mundo?", "Groenlandia", "Madagascar", "Borneo", "Nueva Guinea"],
    ["¿En qué año comenzó la Segunda Guerra Mundial?", "1939", "1914", "1945", "1929"],
    ["¿Cuál es el idioma nativo más hablado del mundo?", "Chino mandarín", "Español", "Inglés", "Hindi"],
    ["¿Qué cordillera separa geográficamente Europa de Asia?", "Montes Urales", "Los Alpes", "El Himalaya", "Los Andes"],
    ["¿En qué ciudad se encuentra la icónica Torre Eiffel?", "París", "Londres", "Berlín", "Roma"],
    ["¿Qué planeta es conocido como el Planeta Rojo?", "Marte", "Venus", "Júpiter", "Mercurio"],
    ["¿Quién pintó la bóveda de la Capilla Sixtina?", "Miguel Ángel", "Leonardo da Vinci", "Donatello", "Sandro Botticelli"],
    ["¿Cuál es el órgano más grande del cuerpo humano?", "La piel", "El hígado", "El intestino grueso", "El pulmón"],
    ["¿En qué país se ubican las famosas Pirámides de Guiza?", "Egipto", "México", "Perú", "Sudán"],
    ["¿Cuál es el lago más profundo de la Tierra?", "Lago Baikal", "Lago Superior", "Lago Titicaca", "Lago Victoria"],
    ["¿Qué instrumento óptico perfeccionó Galileo Galilei para observar el espacio?", "Telescopio", "Microscopio", "Termómetro", "Barómetro"],
    ["¿Quién fue el primer presidente de los Estados Unidos?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"],
    ["¿En qué año comenzó la Revolución Francesa?", "1789", "1776", "1812", "1804"],
    ["¿Cuál es la capital de Japón?", "Tokio", "Kioto", "Osaka", "Yokohama"],
    ["¿A qué grupo de animales pertenece la ballena azul?", "Mamíferos", "Peces", "Reptiles", "Anfibios"],
    ["¿Qué nota musical sigue a Do en la escala diatónica?", "Re", "Mi", "Fa", "Sol"],
    ["¿En qué océano se sitúa la isla de Madagascar?", "Índico", "Atlántico", "Pacífico", "Ártico"],
    ["¿Qué civilización precolombina construyó Machu Picchu?", "Inca", "Maya", "Azteca", "Olmeca"],
    ["¿Cuál es el gas más abundante en la atmósfera terrestre?", "Nitrógeno", "Oxígeno", "Dióxido de carbono", "Argón"],
    ["¿Quién escribió «Don Quijote de la Mancha»?", "Miguel de Cervantes", "Lope de Vega", "Francisco de Quevedo", "Federico García Lorca"],
    ["¿Cuál es la capital de Brasil?", "Brasilia", "Río de Janeiro", "São Paulo", "Salvador de Bahía"],
    ["¿Qué moneda oficial se utiliza en el Reino Unido?", "Libra esterlina", "Euro", "Dólar", "Franco"],
    ["¿En qué año cayó el Imperio Romano de Occidente?", "476 d.C.", "1453 d.C.", "330 d.C.", "100 d.C."],
    ["¿Cuál es el hueso más largo del cuerpo humano?", "Fémur", "Tibia", "Húmero", "Radio"],
    ["¿Qué país regaló la Estatua de la Libertad a Estados Unidos?", "Francia", "Reino Unido", "España", "Alemania"],
    ["¿Cuál es el lugar más seco del planeta Tierra?", "Desierto de Atacama", "Desierto del Sahara", "Desierto de Gobi", "Antártida"],
    ["¿Qué número romano representa el valor 50?", "L", "C", "D", "V"],
    ["¿Cuál es el ave más rápida del mundo en picado?", "Halcón peregrino", "Águila real", "Vencejo", "Paloma"],
    ["¿Qué estrecho de mar separa España de Marruecos?", "Estrecho de Gibraltar", "Estrecho del Bósforo", "Estrecho de Bering", "Estrecho de Magallanes"]
  ],
  "Música": [
    ["¿Qué banda cantaba «Bohemian Rhapsody»?", "Queen", "Pink Floyd", "The Who", "Led Zeppelin"],
    ["¿Quién es conocido como el Rey del Pop?", "Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"],
    ["¿De qué país es el grupo ABBA?", "Suecia", "Noruega", "Reino Unido", "Dinamarca"],
    ["¿Cuántas cuerdas tiene una guitarra clásica?", "6", "4", "5", "8"],
    ["¿Quién canta «Hips Don't Lie»?", "Shakira", "Jennifer Lopez", "Beyoncé", "Rihanna"],
    ["¿Quién canta «Despacito»?", "Luis Fonsi", "Maluma", "J Balvin", "Enrique Iglesias"],
    ["¿De qué ciudad inglesa eran The Beatles?", "Liverpool", "Londres", "Manchester", "Birmingham"],
    ["¿Qué instrumento tocaba Jimi Hendrix?", "Guitarra eléctrica", "Batería", "Piano", "Saxofón"],
    ["¿Qué festival de música se celebra en Benicàssim?", "El FIB", "El Sónar", "El Primavera Sound", "El Mad Cool"],
    ["¿Quién canta «Born in the U.S.A.»?", "Bruce Springsteen", "Bob Dylan", "Billy Joel", "Tom Petty"],
    ["¿Quién interpretaba la famosa canción «Thriller»?", "Michael Jackson", "Prince", "Stevie Wonder", "Lionel Richie"],
    ["¿De qué país es originario el género musical Reggae?", "Jamaica", "Trinidad y Tobago", "Cuba", "Puerto Rico"],
    ["¿Qué compositor sordo creó la Novena Sinfonía?", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Frédéric Chopin"],
    ["¿Qué instrumento de percusión metálico se toca con una baqueta de metal?", "Triángulo", "Platillos", "Maracas", "Xilófono"],
    ["¿Qué artista estadounidense fue apodado 'El Rey del Rock and Roll'?", "Elvis Presley", "Chuck Berry", "Buddy Holly", "Jerry Lee Lewis"],
    ["¿Qué cantante norteamericana lanzó el tema «Bad Romance»?", "Lady Gaga", "Katy Perry", "Britney Spears", "Madonna"],
    ["¿Qué banda británica publicó el icónico álbum «The Dark Side of the Moon»?", "Pink Floyd", "The Rolling Stones", "The Doors", "U2"],
    ["¿Quién es el cantante y líder de la banda irlandesa U2?", "Bono", "The Edge", "Sting", "Chris Martin"],
    ["¿Qué compositor barroco compuso «Las cuatro estaciones»?", "Antonio Vivaldi", "Giuseppe Verdi", "Giacomo Puccini", "Johann Strauss"],
    ["¿Qué cantante española popularizó la canción «Como una ola»?", "Rocío Jurado", "Isabel Pantoja", "Lola Flores", "Luz Casal"],
    ["¿Qué grupo grunge abanderó la canción «Smells Like Teen Spirit»?", "Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"],
    ["¿De qué mítica banda de rock era vocalista Freddie Mercury?", "Queen", "Aerosmith", "Guns N' Roses", "AC/DC"],
    ["¿Quién canta el famoso tema «Rolling in the Deep»?", "Adele", "Amy Winehouse", "Sia", "Dua Lipa"],
    ["¿Qué famoso DJ sueco compuso el éxito de música electrónica «Levels»?", "Avicii", "David Guetta", "Calvin Harris", "Martin Garrix"],
    ["¿Qué tres instrumentos componen principalmente un trío de cuerda clásico?", "Violín, viola y violonchelo", "Guitarra, bajo y batería", "Piano, violín y flauta", "Tres violines"],
    ["¿Qué grupo norteamericano de rock interpretaba «Hotel California»?", "Eagles", "Fleetwood Mac", "Creedence Clearwater Revival", "Lynyrd Skynyrd"],
    ["¿Qué artista española revolucionó la música internacional con su álbum «Motomami»?", "Rosalía", "Aitana", "Karol G", "Bad Gyal"],
    ["¿Qué artista urbano puertorriqueño es conocido como 'El Conejo Malo'?", "Bad Bunny", "Daddy Yankee", "Rauw Alejandro", "Ozuna"],
    ["¿De qué país es originaria la banda de hard rock AC/DC?", "Australia", "Reino Unido", "Estados Unidos", "Irlanda"],
    ["¿Qué cantante pop estadounidense interpretaba «Like a Virgin»?", "Madonna", "Cyndi Lauper", "Tina Turner", "Cher"],
    ["¿En qué barrio neoyorquino surgió el movimiento Hip Hop en los años 70?", "El Bronx", "Brooklyn", "Manhattan", "Queens"],
    ["¿Quién compuso la célebre ópera «La flauta mágica»?", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Richard Wagner", "Franz Schubert"],
    ["¿Qué banda de la 'Movida Madrileña' compuso «La chica de ayer»?", "Nacha Pop", "Los Secretos", "Radio Futura", "Hombres G"],
    ["¿Qué grupo musical madrileño estaba liderado por David Summers?", "Hombres G", "El Canto del Loco", "M-Clan", "Mecano"],
    ["¿Quién era la voz principal del grupo pop español Mecano?", "Ana Torroja", "Amaia Montero", "Marta Sánchez", "Rosana"],
    ["¿Qué icono jamaicano es considerado el gran rey de la música reggae?", "Bob Marley", "Peter Tosh", "Jimmy Cliff", "Shaggy"],
    ["¿Qué artista canadiense triunfó a nivel global con «Blinding Lights»?", "The Weeknd", "Bruno Mars", "Drake", "Post Malone"],
    ["¿Qué virtuoso guitarrista español revolucionó la guitarra flamenca?", "Paco de Lucía", "Vicente Amigo", "Tomatito", "Sabicas"],
    ["¿En qué década nació la subcultura y género musical conocido como Punk?", "Años 70", "Años 50", "Años 90", "Años 60"],
    ["¿En qué mítico festival masivo de 1969 actuaron Hendrix y Janis Joplin?", "Woodstock", "Coachella", "Glastonbury", "Rock in Rio"],
    ["¿Qué artista estadounidense batió récords con su gira 'The Eras Tour'?", "Taylor Swift", "Miley Cyrus", "Selena Gomez", "Ariana Grande"],
    ["¿Qué banda británica está liderada por el vocalista Chris Martin?", "Coldplay", "Keane", "Oasis", "Radiohead"],
    ["¿Quién compuso e interpretaba el clásico tema de los 80 «Purple Rain»?", "Prince", "Michael Jackson", "Stevie Wonder", "David Bowie"],
    ["¿Qué banda de britpop de los hermanos Gallagher compuso «Wonderwall»?", "Oasis", "Blur", "Pulp", "The Verve"],
    ["¿Qué cantautor español es autor de éxitos como «Corazón Partío»?", "Alejandro Sanz", "David Bisbal", "Pablo Alborán", "Manuel Carrasco"],
    ["¿Qué cantante canadiense se dio a conocer mundialmente con «Baby»?", "Justin Bieber", "Shawn Mendes", "Drake", "The Weeknd"],
    ["¿Qué banda norteamericana interpretaba el tema «Sweet Child O' Mine»?", "Guns N' Roses", "Bon Jovi", "Def Leppard", "Whitesnake"],
    ["¿Qué dúo zaragozano compuso la canción «Sin ti no soy nada»?", "Amaral", "La Oreja de Van Gogh", "Ella Baila Sola", "Presuntos Implicados"],
    ["¿Qué célebre cuarteto pop sueco ganó Eurovisión en 1974 con «Waterloo»?", "ABBA", "Roxette", "Europe", "Ace of Base"],
    ["¿Cómo se llama la cantante principal del grupo irlandés The Cranberries?", "Dolores O'Riordan", "Enya", "Sinead O'Connor", "Shirley Manson"]
  ],
  "Cine y series": [
    ["¿Quién dirigió «Titanic» (1997)?", "James Cameron", "Steven Spielberg", "Ridley Scott", "Christopher Nolan"],
    ["¿Cuántas películas tiene la saga principal de Harry Potter?", "8", "6", "7", "10"],
    ["En «Juego de Tronos», ¿qué casa tiene el lema «Se acerca el invierno»?", "Stark", "Lannister", "Targaryen", "Baratheon"],
    ["¿Qué película surcoreana ganó el Óscar a mejor película en 2020?", "Parásitos", "Oldboy", "Train to Busan", "El juego del calamar"],
    ["¿Cómo se llama el protagonista de «Breaking Bad»?", "Walter White", "Jesse Pinkman", "Saul Goodman", "Hank Schrader"],
    ["En «Matrix», ¿de qué color es la pastilla que elige Neo?", "Roja", "Azul", "Verde", "Amarilla"],
    ["¿Quién da vida al capitán Jack Sparrow?", "Johnny Depp", "Orlando Bloom", "Brad Pitt", "Tom Cruise"],
    ["En «La casa de papel», ¿de quién es la máscara que llevan los atracadores?", "Salvador Dalí", "Picasso", "Goya", "Velázquez"],
    ["¿Cómo se llama el robot de Pixar que limpia la Tierra?", "WALL·E", "R2-D2", "Bumblebee", "Baymax"],
    ["¿Quién dirigió «Pulp Fiction»?", "Quentin Tarantino", "Martin Scorsese", "David Fincher", "Tim Burton"],
    ["¿Quién encarna a Iron Man en el Universo Cinematográfico de Marvel?", "Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"],
    ["¿Cómo se llama la nación africana ficticia de la película «Black Panther»?", "Wakanda", "Zamunda", "Genovia", "Latveria"],
    ["¿En qué año se estrenó la primera película de «Star Wars» (Episodio IV)?", "1977", "1980", "1983", "1973"],
    ["¿Qué actor protagoniza la trilogía «Matrix» en el rol de Neo?", "Keanu Reeves", "Laurence Fishburne", "Tom Cruise", "Nicolas Cage"],
    ["¿Qué director de cine dirigió la película «E.T., el extraterrestre»?", "Steven Spielberg", "George Lucas", "James Cameron", "John Carpenter"],
    ["¿En qué importante agencia de publicidad se ambienta la serie «Mad Men»?", "Sterling Cooper", "Ewing Oil", "Waystar Royco", "Dunder Mifflin"],
    ["¿Cómo se llama la taberna que frecuenta Homer Simpson?", "Taberna de Moe", "Joe's Bar", "The Green Dragon", "Central Perk"],
    ["¿En qué ciudad se encuentra la cafetería 'Central Perk' de la serie «Friends»?", "Nueva York", "Los Ángeles", "Chicago", "Boston"],
    ["¿Quién dirigió la trilogía cinematográfica de «El Señor de los Anillos»?", "Peter Jackson", "Guillermo del Toro", "Christopher Nolan", "Sam Raimi"],
    ["¿Qué actor encarnó al Joker en la película «El caballero oscuro» (2008)?", "Heath Ledger", "Joaquin Phoenix", "Jared Leto", "Jack Nicholson"],
    ["¿En qué deporte/juego es una prodigio la protagonista de «Gambito de dama»?", "Ajedrez", "Damas", "Póker", "Go"],
    ["¿En qué año se estrenó en cines la icónica película «Jurassic Park»?", "1993", "1990", "1996", "1989"],
    ["¿Qué actor interpretó al joven Jack Dawson en la película «Titanic»?", "Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Ben Affleck"],
    ["¿Qué famoso agente secreto británico tiene la clave 007?", "James Bond", "Ethan Hunt", "Jason Bourne", "Jack Reacher"],
    ["¿Qué serie animada sigue a un científico alcohólico y a su nieto por el multiverso?", "Rick y Morty", "Futurama", "Padre de Familia", "BoJack Horseman"],
    ["¿En qué pueblo ficticio del estado de Indiana se ambienta «Stranger Things»?", "Hawkins", "Springfield", "Riverdale", "Sunnydale"],
    ["¿Qué película ganó el Óscar a Mejor Película en 1994 superando a «Pulp Fiction»?", "Forrest Gump", "Cadena perpetua", "El rey león", "Braveheart"],
    ["¿Qué actor australiano interpretó a Lobezno (Wolverine) en los X-Men?", "Hugh Jackman", "Ryan Reynolds", "Chris Pratt", "Liev Schreiber"],
    ["¿Qué criatura consumida por el Anillo Único decía la frase «Mi tesoro»?", "Gollum", "Bilbo", "Legolas", "Gimli"],
    ["¿Cómo se llama la muñeca poseída del universo cinematográfico de «Expediente Warren»?", "Annabelle", "Chucky", "Megan", "Tiffany"],
    ["¿Qué actor protagonizó la película «Oppenheimer» de Christopher Nolan?", "Cillian Murphy", "Robert Downey Jr.", "Matt Damon", "Rami Malek"],
    ["¿Cómo se llama el planeta natal destruido de Superman?", "Krypton", "Vegeta", "Tatooine", "Asgard"],
    ["¿Qué actriz israelí interpreta a Wonder Woman en el cine?", "Gal Gadot", "Natalie Portman", "Scarlett Johansson", "Emma Stone"],
    ["¿Quién dirigió la obra maestra del cine de terror «El resplandor»?", "Stanley Kubrick", "Alfred Hitchcock", "Roman Polanski", "John Carpenter"],
    ["¿Qué modelo de coche viaja en el tiempo en «Regreso al futuro»?", "DeLorean", "Mustang", "Chevrolet Corvette", "Cadillac"],
    ["¿Qué clan mafioso está liderado por Tony Soprano en la famosa serie de HBO?", "Los Soprano", "Peaky Blinders", "Boardwalk Empire", "The Wire"],
    ["¿De qué ciudad colombiana era el cartel liderado por Pablo Escobar según «Narcos»?", "Medellín", "Cali", "Bogotá", "Cartagena"],
    ["¿Qué actor protagoniza la trilogía de «El caballero oscuro» encarnando a Batman?", "Christian Bale", "Ben Affleck", "Robert Pattinson", "Michael Keaton"],
    ["¿En qué imperio histórico se ambienta la película «Gladiator»?", "Imperio Romano", "Imperio Griego", "Imperio Persa", "Imperio Egipcio"],
    ["¿Cómo se llama el ogro verde animado que vive en una ciénaga?", "Shrek", "Fiona", "Asno", "Farquaad"],
    ["¿Quién dirigió la película premiada con el Óscar «El laberinto del fauno»?", "Guillermo del Toro", "Alejandro Amenábar", "Pedro Almodóvar", "J.A. Bayona"],
    ["¿Qué actriz encarnó a Katniss Everdeen en «Los Juegos del Hambre»?", "Jennifer Lawrence", "Emma Watson", "Kristen Stewart", "Shailene Woodley"],
    ["¿Qué película animada de Pixar transcurre en la mente de una niña llamada Riley?", "Inside Out (Del revés)", "Soul", "Coco", "Up"],
    ["¿Quién es el director de películas con giros inesperados como «El sexto sentido»?", "M. Night Shyamalan", "David Fincher", "Denis Villeneuve", "Jordan Peele"],
    ["¿Qué serie británica explora las consecuencias oscuras de la tecnología?", "Black Mirror", "Sherlock", "Doctor Who", "The Crown"],
    ["¿Qué actor pone voz a Mario en «Super Mario Bros.: La película» (2023)?", "Chris Pratt", "Jack Black", "Seth Rogen", "Charlie Day"],
    ["¿En qué año se estrenó la primera película animada por ordenador, «Toy Story»?", "1995", "1998", "1992", "2000"],
    ["¿Qué actriz protagonizó el éxito de taquilla «Barbie» en 2023?", "Margot Robbie", "Emma Stone", "Scarlett Johansson", "Florence Pugh"],
    ["¿Qué serie de HBO trata sobre la encarnizada lucha de la familia Roy por un imperio mediático?", "Succession", "Billions", "The White Lotus", "Mad Men"],
    ["¿Cómo se llama el pez payaso protagonista del clásico animado de Pixar?", "Nemo", "Dory", "Marlin", "Gill"]
  ],
  "Deportes": [
    ["¿Cuántos jugadores hay por equipo en el campo en un partido de fútbol?", "11", "9", "10", "12"],
    ["¿Qué selección ganó el Mundial de fútbol de 2010?", "España", "Países Bajos", "Alemania", "Brasil"],
    ["¿En qué deporte se consigue un «birdie»?", "Golf", "Tenis", "Béisbol", "Rugby"],
    ["¿Cuántos puntos vale un tiro libre en baloncesto?", "1", "2", "3", "4"],
    ["¿En qué ciudad se celebraron los Juegos Olímpicos de 1992?", "Barcelona", "Madrid", "Atlanta", "Seúl"],
    ["¿Cuántos anillos tiene la bandera olímpica?", "5", "4", "6", "7"],
    ["¿En qué deporte destacó Michael Jordan?", "Baloncesto", "Béisbol", "Fútbol americano", "Tenis"],
    ["¿Cuántos minutos dura el tiempo reglamentario de un partido de fútbol?", "90", "80", "100", "60"],
    ["¿Qué país es famoso por el sumo?", "Japón", "China", "Corea del Sur", "Tailandia"],
    ["¿Cuántos jugadores de un equipo hay en pista en baloncesto?", "5", "6", "7", "4"],
    ["¿Quién ha ganado más torneos de Grand Slam en la historia del tenis masculino?", "Novak Djokovic", "Rafael Nadal", "Roger Federer", "Andy Murray"],
    ["¿En qué deporte destacó internacionalmente el español Pau Gasol?", "Baloncesto", "Balonmano", "Tenis", "Voleibol"],
    ["¿Cuál es la distancia exacta de una carrera de maratón oficial?", "42,195 km", "40 km", "50 km", "21 km"],
    ["¿Qué piloto de Fórmula 1 ostenta 7 títulos mundiales junto a Michael Schumacher?", "Lewis Hamilton", "Max Verstappen", "Fernando Alonso", "Sebastian Vettel"],
    ["¿En qué club de fútbol jugó la mayor parte de su carrera profesional Lionel Messi?", "FC Barcelona", "Paris Saint-Germain", "Inter de Miami", "Newell's Old Boys"],
    ["¿Qué país albergó el Mundial de Fútbol de 2018?", "Rusia", "Brasil", "Catar", "Sudáfrica"],
    ["¿Qué nadador ostenta el récord absoluto de medallas de oro olímpicas?", "Michael Phelps", "Ian Thorpe", "Mark Spitz", "Ryan Lochte"],
    ["¿Qué club español ha ganado más Champions League / Copas de Europa?", "Real Madrid", "FC Barcelona", "Atlético de Madrid", "Sevilla FC"],
    ["¿En qué deporte se emplea una raqueta ligera y un volante o pluma?", "Bádminton", "Tenis de mesa", "Squash", "Pádel"],
    ["¿Cuál es el torneo de tenis sobre hierba más antiguo y prestigioso del mundo?", "Wimbledon", "Roland Garros", "US Open", "Open de Australia"],
    ["¿Qué atleta jamaicano ostenta el récord mundial de los 100 metros lisos?", "Usain Bolt", "Yohan Blake", "Asafa Powell", "Tyson Gay"],
    ["¿Cuántos cuartos de 12 minutos se juegan en un partido de la NBA?", "4", "2", "3", "5"],
    ["¿Sobre qué superficie se juega el torneo de Grand Slam de Roland Garros?", "Tierra batida", "Césped", "Pista dura", "Moqueta"],
    ["¿Qué selección nacional masculina ganó el Mundial de Baloncesto en 2006 y 2019?", "España", "Estados Unidos", "Argentina", "Francia"],
    ["¿Qué piloto español ganó dos Mundiales de Fórmula 1 con Renault?", "Fernando Alonso", "Carlos Sainz", "Pedro de la Rosa", "Marc Gené"],
    ["¿Qué deporte invernal combina el esquí de fondo con el tiro con carabina?", "Biatlón", "Combinada nórdica", "Skeleton", "Curling"],
    ["¿De qué país asiático es originario el arte marcial del Judo?", "Japón", "China", "Corea del Sur", "Tailandia"],
    ["¿Qué mariscal de campo lideró a los Kansas City Chiefs a ganar la Super Bowl LVII?", "Patrick Mahomes", "Tom Brady", "Aaron Rodgers", "Jalen Hurts"],
    ["¿Qué ciclista español ganó 5 Tours de Francia de forma consecutiva?", "Miguel Induráin", "Alberto Contador", "Carlos Sastre", "Pedro Delgado"],
    ["¿En qué deporte se compite internacionalmente por la 'Copa América'?", "Vela", "Fútbol", "Rugby", "Polo"],
    ["¿Cuántos golpes por debajo del par del hoyo representa un 'Eagle' en golf?", "2 golpes menos", "1 golpe menos", "3 golpes menos", "4 golpes menos"],
    ["¿Qué luchador hispano-georgiano se proclamó campeón peso pluma de la UFC en 2024?", "Ilia Topuria", "Joel Álvarez", "Enrique Marín", "Alexander Volkanovski"],
    ["¿Qué club de fútbol de Londres es conocido popularmente como los 'Gunners'?", "Arsenal", "Chelsea", "Tottenham", "West Ham"],
    ["¿En qué ciudad europea se celebraron los Juegos Olímpicos de Verano de 2024?", "París", "Londres", "Atenas", "Roma"],
    ["¿Qué tenista española ganó el torneo de Roland Garros 2016 y Wimbledon 2017?", "Garbiñe Muguruza", "Arantxa Sánchez Vicario", "Conchita Martínez", "Paula Badosa"],
    ["¿Cuántos jugadores por equipo están en pista durante un partido de voleibol?", "6", "5", "7", "11"],
    ["¿En qué deporte de raqueta destaca la campeona olímpica española Carolina Marín?", "Bádminton", "Tenis", "Pádel", "Squash"],
    ["¿Qué país ha ganado la Copa Mundial de Fútbol Masculino en más ocasiones (5 veces)?", "Brasil", "Alemania", "Italia", "Argentina"],
    ["¿Qué legendario jugador de baloncesto llevaba el dorsal 23 en los Chicago Bulls?", "Michael Jordan", "Kobe Bryant", "LeBron James", "Magic Johnson"],
    ["¿En qué deporte se realiza un 'pleno' o 'strike' al derribar diez bolos?", "Bolos (Bowling)", "Béisbol", "Golf", "Billar"],
    ["¿En qué complejo deportivo de Londres se juega el torneo de Wimbledon?", "All England Club", "Flushing Meadows", "Roland Garros", "Melbourne Park"],
    ["¿Qué famoso boxeador decía «Vuela como una mariposa, pica como una abeja»?", "Muhammad Ali", "Mike Tyson", "Floyd Mayweather", "George Foreman"],
    ["¿Qué selección nacional de rugby es famosa por realizar la danza 'Haka'?", "Nueva Zelanda (All Blacks)", "Australia", "Sudáfrica", "Inglaterra"],
    ["¿Cuántos minutos dura la prórroga completa en un partido de fútbol reglamentario?", "30 minutos", "15 minutos", "20 minutos", "10 minutos"],
    ["¿En qué disciplina del motor ha ganado Marc Márquez múltiples títulos mundiales?", "Motociclismo (MotoGP)", "Fórmula 1", "Rally Dakar", "Motocross"],
    ["¿Qué estilo de natación se realiza sobre la espalda impulsándose hacia atrás?", "Espalda", "Braza", "Mariposa", "Crawl"],
    ["¿Qué selección de fútbol se proclamó campeona del mundo en Catar 2022?", "Argentina", "Francia", "Croacia", "Marruecos"],
    ["¿Qué gimnasta artística estadounidense ostenta más medallas mundiales que nadie?", "Simone Biles", "Aly Raisman", "Gabby Douglas", "McKayla Maroney"],
    ["¿En qué año ganó la selección española de fútbol su segunda Eurocopa en Viena?", "2008", "2010", "2012", "2004"],
    ["¿Qué estilo de natación es considerado técnicamente el más rápido?", "Crawl (estilo libre)", "Mariposa", "Braza", "Espalda"]
  ],
   "Bar y copas": [
    ["¿De qué país es originario el mojito?", "Cuba", "México", "España", "Brasil"],
    ["¿Qué licor es la base del Margarita?", "Tequila", "Ron", "Vodka", "Ginebra"],
    ["¿Qué ingredientes lleva una piña colada?", "Ron, coco y piña", "Tequila, lima y sal", "Vodka y naranja", "Ginebra y tónica"],
    ["¿Qué planta da el sabor amargo a la cerveza?", "El lúpulo", "La menta", "El romero", "El laurel"],
    ["¿De qué país es el vodka Absolut?", "Suecia", "Rusia", "Polonia", "Finlandia"],
    ["¿Qué lleva un gin-tonic además de ginebra?", "Agua tónica", "Soda", "Refresco de cola", "Zumo de naranja"],
    ["¿Qué bebida es la base de la sangría?", "Vino tinto", "Cerveza", "Sidra", "Cava"],
    ["¿De qué fruta se obtiene la sidra?", "Manzana", "Pera", "Uva", "Melocotón"],
    ["¿Qué lleva un «cuba libre»?", "Ron y cola", "Whisky y soda", "Vodka y tónica", "Ginebra y limón"],
    ["¿De qué planta se destila el tequila?", "Agave", "Caña de azúcar", "Cebada", "Maíz"],
    ["¿Qué destilado transparente es la base del cóctel 'Bloody Mary'?", "Vodka", "Ginebra", "Ron", "Tequila"],
    ["¿Qué ingrediente botánico le da su característico sabor dominante a la ginebra?", "Enebro", "Cardamomo", "Anís", "Cilantro"],
    ["¿Qué licor amargo italiano le da el color rojo y sabor característico al Negroni?", "Campari", "Aperol", "Cynar", "Fernet"],
    ["¿De qué país latinoamericano disputan la paternidad original del Pisco Sour?", "Perú y Chile", "Colombia y Venezuela", "Argentina y Uruguay", "México y Cuba"],
    ["¿Qué porcentaje de alcohol aproximado tiene una cerveza rubia comercial habitual?", "4,5% - 5,5%", "12%", "2%", "8,5%"],
    ["¿Qué tres bebidas componen el clásico cóctel italiano Negroni a partes iguales?", "Ginebra, vermut rojo y Campari", "Vodka, tónica y lima", "Ron, cola y limón", "Whisky, vermut blanco y tónica"],
    ["¿Qué ingrediente principal le otorga su color rojo al cóctel Bloody Mary?", "Zumo de tomate", "Zumo de arándanos", "Granadina", "Campari"],
    ["¿Qué licor italiano tiene un marcado sabor a almendra o hueso de albaricoque?", "Amaretto", "Frangelico", "Limoncello", "Sambuca"],
    ["¿De qué cereal malteado se produce el whisky escocés de malta (Single Malt)?", "Cebada", "Maíz", "Centeno", "Trigo"],
    ["¿Qué cóctel clásico lleva whisky, angostura, un terrón de azúcar y piel de naranja?", "Old Fashioned", "Whisky Sour", "Manhattan", "Sazerac"],
    ["¿Qué tipo de vino con burbujas tiene Denominación de Origen protegida en la región francesa de Reims?", "Champagne", "Cava", "Prosecco", "Lambrusco"],
    ["¿En qué región de España se produce el famoso vino fortalecido en criaderas y soleras?", "Jerez", "La Rioja", "Ribera del Duero", "Priorat"],
    ["¿Qué fruta cítrica se utiliza clásicamente para aromatizar un Gin-Tonic con su corteza?", "Limón o lima", "Naranja dulce", "Pomelo", "Fresa"],
    ["¿Cómo se le llama popularmente a la espuma cremosa que corona una caña bien tirada?", "Gualdrapa o crema", "Poso", "Carbónico", "Sedimento"],
    ["¿Qué licor de hierbas alemán es famoso por tener un ciervo en su etiqueta?", "Jägermeister", "Becherovka", "Chartreuse", "Absenta"],
    ["¿Qué hierba aromática fresca es indispensable para preparar un buen Mojito?", "Hierbabuena o menta", "Albahaca", "Romero", "Cilantro"],
    ["¿Qué destilado de caña brasileño es el ingrediente alcohólico de la Caipirinha?", "Cachaza (Cachaça)", "Pisco", "Tequila", "Ron añejo"],
    ["¿Qué tipo de copa alargada y estrecha se utiliza para servir cava o champán?", "Copa flauta", "Copa balón", "Vaso de tubo", "Copa Martini"],
    ["¿De qué fruto cítrico se elabora el tradicional licor italiano Limoncello?", "Limón", "Mandarina", "Lima", "Naranja amarga"],
    ["¿Qué cóctel combina vodka, cerveza de jengibre (ginger beer) y zumo de lima?", "Moscow Mule", "Dark 'n' Stormy", "Tom Collins", "Espresso Martini"],
    ["¿En qué país del Caribe nació históricamente la destilación del Ron?", "Barbados / Jamaica / Cuba", "España", "Estados Unidos", "Irlanda"],
    ["¿Qué aperitivo italiano de color naranja brillante es la base del popular 'Spritz'?", "Aperol", "Campari", "Fernet", "Martini Bianco"],
    ["¿Qué cóctel combina vodka, licor de café y café expreso recién tirado?", "Espresso Martini", "White Russian", "Black Russian", "Irish Coffee"],
    ["¿Qué ingrediente alcohólico se le añade a un 'Café Irlandés' tradicional?", "Whisky irlandés", "Brandy", "Ron añejo", "Anís seco"],
    ["¿De qué fruta se extrae el zumo para elaborar un cóctel Mimosa junto con vino espumoso?", "Naranja", "Melocotón", "Piña", "Arándano"],
    ["¿Qué nombre recibe el vaso alto y recto empleado habitualmente para servir combinados?", "Vaso de tubo o Highball", "Copa balón", "Vaso Old Fashioned", "Chupito"],
    ["¿Qué graduación alcohólica estándar suele presentar una botella de whisky o ginebra?", "40%", "20%", "60%", "15%"],
    ["¿Qué variedad de uva tinta es la más representativa de los vinos de la D.O. Ribera del Duero?", "Tempranillo (Tinta del País)", "Garnacha", "Cabernet Sauvignon", "Mencía"],
    ["¿En qué copa cónica se sirve habitualmente un Dry Martini decorado con una aceituna?", "Copa Martini", "Copa flauta", "Copa balón", "Vaso ancho"],
    ["¿Qué licor de avellana es famoso por tener una botella con la forma de un monje?", "Frangelico", "Amaretto", "Baileys", "Kahlúa"],
    ["¿De qué país es originaria la famosa cerveza negra de tipo stout Guinness?", "Irlanda", "Escocia", "Inglaterra", "Bélgica"],
    ["¿Qué refresco se mezcla tradicionalmente con ginebra en un combinado clásico?", "Agua tónica", "Refresco de cola", "Sprite", "Gaseosa"],
    ["¿Cómo se denomina el proceso biológico que transforma el azúcar del mosto en alcohol?", "Fermentación", "Destilación", "Maceración", "Decantación"],
    ["¿Qué variedad de uva blanca es la estrella en la D.O. Rías Baixas de Galicia?", "Albariño", "Verdejo", "Godello", "Chardonnay"],
    ["¿Qué variedad de uva blanca es la más característica de la D.O. Rueda?", "Verdejo", "Albariño", "Macabeo", "Sauvignon Blanc"],
    ["¿Qué bebida alcohólica se obtiene tras fermentar el zumo de manzana?", "Sidra", "Cerveza", "Hidromiel", "Pisco"],
    ["¿Cómo se denomina el arte profesional de mezclar y preparar cócteles en una barra?", "Mixología o coctelería", "Sommelería", "Enología", "Barismo"],
    ["¿Qué cóctel a base de tequila, zumo de lima y licor de naranja se sirve con sal en el borde?", "Margarita", "Paloma", "Tequila Sunrise", "Bloody Mary"],
    ["¿Qué destilado mexicano se elabora artesanalmente cociendo piñas de agave en hornos de piedra?", "Mezcal", "Tequila", "Sotol", "Pisco"],
    ["¿Qué bebida se obtiene de la fermentación de la miel mezclada con agua?", "Hidromiel", "Sidra", "Absenta", "Kombucha"]
  ],
  "Valladolid y España": [
    ["¿Cómo se conoce coloquialmente a Valladolid?", "Pucela", "La Perla", "Vallecas", "La Muy Noble"],
    ["¿Qué río atraviesa Valladolid?", "El Pisuerga", "El Tajo", "El Ebro", "El Guadalquivir"],
    ["¿De qué color es la camiseta del Real Valladolid?", "Blanca y violeta", "Roja y blanca", "Azul y amarilla", "Verde y negra"],
    ["¿Qué museo de Valladolid está en el Colegio de San Gregorio?", "El Museo Nacional de Escultura", "El Museo del Prado", "El Museo Reina Sofía", "El Museo Guggenheim"],
    ["¿Qué autor del Quijote vivió en Valladolid?", "Miguel de Cervantes", "Lope de Vega", "Quevedo", "Calderón de la Barca"],
    ["¿Qué carne asada es típica de Castilla y León?", "El lechazo", "El cochinillo de Teruel", "La carne de buey gallega", "El pollo en pepitoria"],
    ["¿Cuál es la montaña más alta de España?", "El Teide", "El Mulhacén", "El Aneto", "Peña Vieja"],
    ["¿Cuántas comunidades autónomas tiene España?", "17", "15", "19", "50"],
    ["¿Qué mar baña la costa este de España?", "El Mediterráneo", "El Cantábrico", "El Mar del Norte", "El Mar Negro"],
    ["¿Qué fiesta con procesiones se celebra en Valladolid antes de Pascua?", "La Semana Santa", "Las Fallas", "Los Sanfermines", "La Tomatina"],
    ["¿En qué céntrica plaza de Valladolid se encuentra la estatua del Conde Ansúrez?", "Plaza Mayor", "Plaza de Zorrilla", "Plaza de España", "Plaza de San Pablo"],
    ["¿Quién es considerado el fundador histórico de la ciudad de Valladolid?", "El Conde Pedro Ansúrez", "Felipe II", "Alfonso VI", "El Cid Campeador"],
    ["¿Qué rey español nació en el Palacio Pimentel de Valladolid en 1527?", "Felipe II", "Carlos I", "Felipe III", "Fernando el Católico"],
    ["¿Qué famoso parque céntrico de Valladolid alberga pavorreales en libertad?", "Campo Grande", "Parque del Mediodía", "Parque de las Norias", "Parque de las Contiendas"],
    ["¿Cómo se llama el estadio de fútbol del Real Valladolid?", "Estadio José Zorrilla", "Estadio Nuevo Arcángel", "Estadio de la Balastera", "El Helmántico"],
    ["¿Qué famosa obra teatral sobre Don Juan escribió el vallisoletano José Zorrilla?", "Don Juan Tenorio", "La vida es sueño", "Fuenteovejuna", "El alcalde de Zalamea"],
    ["¿En qué período fue Valladolid capital oficial del Imperio Español bajo Felipe III?", "De 1601 a 1606", "De 1500 a 1510", "De 1650 a 1660", "De 1492 a 1500"],
    ["¿Qué importante certamen de cine de autor se celebra anualmente en Valladolid?", "SEMINCI", "Festival de San Sebastián", "Festival de Sitges", "Málaga Film Festival"],
    ["¿Cuál es el puente de piedra más antiguo que cruza el río Pisuerga en Valladolid?", "Puente Mayor", "Puente del Poniente", "Puente de Isabel la Católica", "Puente de Hispanidad"],
    ["¿Qué famoso pasaje comercial cubierto del siglo XIX se conserva en Valladolid?", "Pasaje Gutiérrez", "Pasaje de la Victoria", "Pasaje del Comercio", "Pasaje del Norte"],
    ["¿Qué canal de ingeniería hidráulica del siglo XVIII discurre por la provincia de Valladolid?", "Canal de Castilla", "Canal de Isabel II", "Canal Imperial de Aragón", "Canal del Duero"],
    ["¿Qué río vallisoletano de menor caudal desemboca en el Pisuerga dentro de la ciudad?", "El Esgueva", "El Tormes", "El Carrión", "El Arlanza"],
    ["¿En qué edificio vallisoletano contrajeron matrimonio los Reyes Católicos en 1469?", "Palacio de los Vivero", "Iglesia de San Pablo", "Catedral de Valladolid", "Iglesia de la Antigua"],
    ["¿Qué dos célebres clubes de rugby de Valladolid disputan el derbi local?", "VRAC y El Salvador", "Lexus Alcobendas y Burgos", "Santboiana y Cisneros", "Ordizia y Aparejadores"],
    ["¿En qué edificio histórico vallisoletano falleció Cristóbal Colón en 1506?", "Casa de Colón (Convento de San Francisco)", "Palacio Real", "Colegio de Santa Cruz", "Castillo de Simancas"],
    ["¿En qué importante plaza madrileña se sitúan el edificio España y el monumento a Cervantes?", "Plaza de España", "Plaza Mayor", "Puerta del Sol", "Plaza de Cibeles"],
    ["¿Cuál es la capital oficial de la comunidad autónoma de Galicia?", "Santiago de Compostela", "A Coruña", "Vigo", "Ourense"],
    ["¿En qué ciudad andaluza se encuentra el complejo palaciego de la Alhambra?", "Granada", "Sevilla", "Córdoba", "Málaga"],
    ["¿Qué catedral gótica española es célebre mundialmente por sus espectaculares vidrieras?", "Catedral de León", "Catedral de Burgos", "Catedral de Toledo", "Catedral de Santiago"],
    ["¿En qué ciudad española se ubica el famoso Acueducto romano de doble arquería?", "Segovia", "Ávila", "Salamanca", "Soria"],
    ["¿Qué parque nacional andaluz es una de las reservas de humedales más importantes de Europa?", "Doñana", "Monfragüe", "Cabañeros", "Ordesa y Monte Perdido"],
    ["¿Cuál es la isla de mayor extensión del archipiélago Canario?", "Tenerife", "Gran Canaria", "Fuerteventura", "Lanzarote"],
    ["¿Qué genial arquitecto modernista diseñó el Templo Expiatorio de la Sagrada Familia?", "Antoni Gaudí", "Lluís Domènech i Montaner", "Josep Puig i Cadafalch", "Santiago Calatrava"],
    ["¿En qué ciudad hispalense o andaluza se conserva la mítica Mezquita-Catedral?", "Córdoba", "Sevilla", "Granada", "Jaén"],
    ["¿Qué importante sistema montañoso separa Castilla y León de la Comunidad de Madrid?", "Sistema Central (Sierra de Guadarrama)", "Sierra Morena", "Cordillera Cantábrica", "Pirineos"],
    ["¿En qué fiesta valenciana se queman monumentos artísticos de cartón piedra el 19 de marzo?", "Las Fallas", "La Tomatina", "La Feria de Abril", "Los Sanfermines"],
    ["¿En qué ciudad castellana fundó Alfonso IX la universidad más antigua de España en activo?", "Salamanca", "Valladolid", "Palencia", "Zamora"],
    ["¿Qué histórica denominación de origen vitivinícola vallisoletana destaca por sus vinos tintos?", "D.O. Ribera del Duero", "D.O. Rías Baixas", "D.O. Valdepeñas", "D.O. Somontano"],
    ["¿En qué castillo vallisoletano se encuentra instalado el Museo Provincial del Vino?", "Castillo de Peñafiel", "Castillo de La Mota", "Castillo de Simancas", "Castillo de Fuensaldaña"],
    ["¿En qué fortaleza histórica vallisoletana se custodia el Archivo General de Simancas?", "Castillo de Simancas", "Castillo de Peñafiel", "Castillo de La Mota", "Castillo de Tiedra"],
    ["¿En qué villa vallisoletana se firmó el tratado que dividió el Nuevo Mundo entre España y Portugal?", "Tordesillas", "Medina del Campo", "Peñafiel", "Olmedo"],
    ["¿Qué emblemático castillo domina la villa de Medina del Campo en Valladolid?", "Castillo de La Mota", "Castillo de Simancas", "Castillo de Peñafiel", "Castillo de Curiel"],
    ["¿Qué municipio vallisoletano es famoso por sus bodegas y la producción de vino clarete D.O.?", "Cigales", "Rueda", "Peñafiel", "Olmedo"],
    ["¿Qué personaje literario da título a la célebre obra dramática de Lope de Vega ambientada en Valladolid?", "El Caballero de Olmedo", "El Licenciado Vidriera", "El Buscón", "Don Gil de las Calzas Verdes"],
    ["¿Qué gran río transcurre por la provincia de Valladolid tras recibir las aguas del Pisuerga?", "El Duero", "El Ebro", "El Tajo", "El Miño"],
    ["¿Qué plato de legumbres elaborado con garbanzos y carnes es el más emblemático de Madrid?", "Cocido madrileño", "Fabada asturiana", "Escudella", "Puchero andaluz"],
    ["¿Qué género musical y de baile tradicional andaluz es Patrimonio de la Humanidad?", "El flamenco", "La jota", "La muñeira", "El chotis"],
    ["¿En qué gran museo madrileño se expone la obra «Las Meninas» de Diego Velázquez?", "Museo del Prado", "Museo Reina Sofía", "Museo Thyssen-Bornemisza", "Real Academia de Bellas Artes"],
    ["¿Qué famosa escultura íbera de piedra se expone en el Museo Arqueológico Nacional en Madrid?", "La Dama de Elche", "La Dama de Baza", "La Venus de Milo", "La Bicha de Balazote"],
    ["¿En qué plaza vallisoletana se encuentra la fachada plateresca de la Iglesia de San Pablo?", "Plaza de San Pablo", "Plaza Mayor", "Plaza Vieja", "Plaza del Salvador"]
  ]
};
